open-runtimes/open-runtimes

README.md
runtimes/node-17.0/README.md
runtimes/node-17.0/example/index.js

Improved readmes, and moved some sections. This will help implement new runtimes faster without duplicating a lot of sections.

Feat: Updated Readmes

---

build.sh
runtimes/dart-2.12/README.md
runtimes/dart-2.13/README.md
runtimes/dart-2.14/README.md
runtimes/deno-1.12/README.md
runtimes/deno-1.13/README.md
runtimes/deno-1.14/README.md
runtimes/node-14.5/README.md
runtimes/node-15.5/README.md
runtimes/node-16.0/README.md
runtimes/node-17.0/README.md
runtimes/php-8.0/README.md
runtimes/php-8.1/README.md
runtimes/python-3.8/README.md
runtimes/python-3.9/README.md
runtimes/ruby-3.0/README.md
runtimes/ruby-3.1/README.md

After pushing to Docker Hub, Manual QA showed some mistakes in readmes.

WIP: Fix examples

---

.travis.yml
tests.sh

Wait until defined server process is started before executing tests

Feat improve test wait

---

runtimes/dart-2.12/build.sh
runtimes/dart-2.13/build.sh
runtimes/dart-2.14/build.sh
runtimes/dart-2.15/build.sh
runtimes/deno-1.12/build.sh
runtimes/deno-1.13/build.sh
runtimes/deno-1.14/build.sh
runtimes/node-14.5/build.sh
runtimes/node-15.5/build.sh
runtimes/node-16.0/build.sh
runtimes/node-17.0/build.sh
runtimes/php-8.0/build.sh
runtimes/php-8.1/build.sh
runtimes/python-3.10/build.sh
runtimes/python-3.8/build.sh
runtimes/python-3.9/build.sh
runtimes/ruby-3.0/build.sh
runtimes/ruby-3.1/build.sh
runtimes/swift-5.5/build.sh

- Fixes integration errors where a build step fails but the script exits with a success code

Fail build if any command fails

---

runtimes/dart-2.12/build.sh
runtimes/dart-2.13/build.sh
runtimes/dart-2.14/build.sh
runtimes/dart-2.15/build.sh

Fix some bugs in the dart runtime

feat: fix dart runtimes

---

runtimes/python-3.10/Dockerfile
runtimes/python-3.10/server.py
runtimes/python-3.10/start.sh
runtimes/python-3.8/Dockerfile
runtimes/python-3.8/server.py
runtimes/python-3.8/start.sh
runtimes/python-3.9/Dockerfile
runtimes/python-3.9/server.py
runtimes/python-3.9/start.sh

This now works:
TODO: Implementation missing in 3.9, 3.8

Fix: Python relative imports

---

runtimes/node-14.5/README.md
runtimes/node-14.5/server.js
runtimes/node-15.5/README.md
runtimes/node-15.5/server.js
runtimes/node-16.0/README.md
runtimes/node-16.0/server.js
runtimes/node-17.0/README.md
runtimes/node-17.0/server.js

Reverts open-runtimes/open-runtimes#51

Revert "Docs: Node reserved key"

---

runtimes/dart-2.12/server.dart
runtimes/dart-2.13/server.dart
runtimes/dart-2.14/server.dart
runtimes/dart-2.15/server.dart
runtimes/dart-2.16/server.dart
runtimes/deno-1.12/server.ts
runtimes/deno-1.13/server.ts
runtimes/deno-1.14/server.ts
runtimes/node-14.5/server.js
runtimes/node-15.5/server.js
runtimes/node-16.0/server.js
runtimes/node-17.0/server.js
runtimes/php-8.0/server.php
runtimes/php-8.1/server.php
runtimes/python-3.10/server.py
runtimes/python-3.8/server.py
runtimes/python-3.9/server.py
runtimes/ruby-3.0/server.rb
runtimes/ruby-3.1/server.rb
runtimes/swift-5.5/Sources/App/routes.swift

This information is no longer needed in the body. Appwrite uses response code now.

Feat: Remove code from error body

---

runtimes/dart-2.12/server.dart
runtimes/dart-2.13/server.dart
runtimes/dart-2.14/server.dart
runtimes/dart-2.15/server.dart
runtimes/dart-2.16/server.dart
runtimes/deno-1.12/server.ts
runtimes/deno-1.13/server.ts
runtimes/deno-1.14/server.ts
runtimes/node-14.5/server.js
runtimes/node-15.5/server.js
runtimes/node-16.0/server.js
runtimes/node-17.0/server.js
runtimes/php-8.0/server.php
runtimes/php-8.1/server.php
runtimes/python-3.10/server.py
runtimes/python-3.8/server.py
runtimes/python-3.9/server.py
runtimes/ruby-3.0/server.rb
runtimes/ruby-3.1/server.rb
runtimes/swift-5.5/Sources/App/routes.swift

4XX in Appwrite indicates client error, but this is error in executor communication, happening between servers.

Feat: Rename http codes

---

runtimes/deno-1.12/start.sh
runtimes/deno-1.13/start.sh
runtimes/deno-1.14/start.sh

This is patch until we release SDKs that allow uploading files from buffer.

Feat: Allow file write in Deno

---

runtimes/deno-1.21/README.md
runtimes/deno-1.24/README.md

Updated tags to correct format

Update deno runtime tags

---

runtimes/dotnet-3.1/README.md
runtimes/dotnet-6.0/README.md

Made corrections in the .NET Core 3.1 and .NET 6.0 docs

Add corrections in .NET runtimes' docs

---

runtimes/dart-2.18/README.md
runtimes/dart-2.18/example/lib/main.dart
runtimes/dart-2.18/function_types.dart
runtimes/dart-2.18/server.dart
runtimes/java-11.0/gradle/wrapper/gradle-wrapper.properties
runtimes/java-17.0/build.gradle
runtimes/java-17.0/gradle/wrapper/gradle-wrapper.properties
runtimes/java-18.0/build.gradle
runtimes/java-18.0/gradle/wrapper/gradle-wrapper.properties
runtimes/java-8.0/gradle/wrapper/gradle-wrapper.properties
runtimes/kotlin-1.6/gradle/wrapper/gradle-wrapper.properties
tests/dart-2.18/lib/tests.dart

- Update Gradle for all JVM runtimes
- Update source compatibility for Java 17 + 18 to allow using version specific features
Existing tests

Feat java updates

---

runtimes/node-18.0/server.js
runtimes/python-3.10/server.py
tests-v3.sh
tests/BaseV3.php
tests/resources/functions/node-18.0/tests.js
tests/resources/functions/python-3.10/tests.py

Fix node and python v3 to support new tests

Fix: Node & Python

---

runtimes/node-18.0/server.js
runtimes/python-3.10/server.py
tests/BaseV3.php
tests/resources/functions/python-3.10/tests.py

Puts all changes from other PRs into one. This PR helps remove those changes from other PRs, such as Deno or PHP. No need for JS&Python changes to be in those.

Fix: Node&Python v3 changes

---

.travis.yml
build.sh
tests.sh

CI/CD started failing with:
```
0.02s$ docker buildx create --use
unknown flag: --use
See 'docker --help'.
```
This PR makes it work again.

Fix: CI/CD docker buildx

---

.gitignore
.travis.yml
composer.lock
runtimes/dotnet-8.0/.dockerignore
runtimes/dotnet-8.0/.env
runtimes/dotnet-8.0/.gitignore
runtimes/dotnet-8.0/Dockerfile
runtimes/dotnet-8.0/DotNetRuntime.csproj
runtimes/dotnet-8.0/DotNetRuntime.sln
runtimes/dotnet-8.0/README.md
runtimes/dotnet-8.0/docker-compose.yml
runtimes/dotnet-8.0/example/Function.csproj
runtimes/dotnet-8.0/example/Index.cs
runtimes/dotnet-8.0/helpers/after-build.sh
runtimes/dotnet-8.0/helpers/before-build.sh
runtimes/dotnet-8.0/helpers/before-start.sh
runtimes/dotnet-8.0/helpers/build.sh
runtimes/dotnet-8.0/helpers/start.sh
runtimes/dotnet-8.0/src/CustomResponse.cs
runtimes/dotnet-8.0/src/Program.cs
runtimes/dotnet-8.0/src/RuntimeContext.cs
runtimes/dotnet-8.0/src/RuntimeOutput.cs
runtimes/dotnet-8.0/src/RuntimeRequest.cs
runtimes/dotnet-8.0/src/RuntimeResponse.cs
tests/resources/functions/dotnet-8.0/Function.csproj
tests/resources/functions/dotnet-8.0/Tests.cs

Creates runtime for .NET 8 (the new LTS release)
- Followed instructions in Contributing Guide to build an image of the runtime
- Followed example in runtime readme to test (got a successful response as expected)

Feat: Add dotnet-8.0 runtime

---

composer.json
runtimes/php-8.0/composer.json
runtimes/php-8.0/example/composer.json
runtimes/php-8.1/composer.json
runtimes/php-8.1/example/composer.json
runtimes/php-8.2/composer.json
runtimes/php-8.2/example/composer.json
tests/resources/functions/php-8.0/composer.json
tests/resources/functions/php-8.1/composer.json
tests/resources/functions/php-8.2/composer.json

Appwrite voice aims to showcase power of open source community as a whole, not individuals. Ensuring no authors are mentioned in runtimes allows us to present exactly that.

Feat: Remove authors

---

.gitpod.yml
README.md
tests.sh

Fix: Local development

---

runtimes/node-18.0/Dockerfile
runtimes/node-18.0/src/logger.js
runtimes/node-18.0/src/server.js

Re-implementation of log files but using streams

Log files: Stream support

---

README.md
runtimes/kotlin-1.6/src/main/kotlin/io/openruntimes/kotlin/RuntimeOutput.kt
runtimes/kotlin-1.6/src/main/kotlin/io/openruntimes/kotlin/RuntimeRequest.kt
runtimes/kotlin-1.6/src/main/kotlin/io/openruntimes/kotlin/RuntimeResponse.kt
runtimes/kotlin-1.6/src/main/kotlin/io/openruntimes/kotlin/Server.kt
runtimes/kotlin-1.8/src/main/kotlin/io/openruntimes/kotlin/RuntimeOutput.kt
runtimes/kotlin-1.8/src/main/kotlin/io/openruntimes/kotlin/RuntimeRequest.kt
runtimes/kotlin-1.8/src/main/kotlin/io/openruntimes/kotlin/RuntimeResponse.kt
runtimes/kotlin-1.8/src/main/kotlin/io/openruntimes/kotlin/Server.kt
runtimes/kotlin-1.9/src/main/kotlin/io/openruntimes/kotlin/RuntimeOutput.kt
runtimes/kotlin-1.9/src/main/kotlin/io/openruntimes/kotlin/RuntimeRequest.kt
runtimes/kotlin-1.9/src/main/kotlin/io/openruntimes/kotlin/RuntimeResponse.kt
runtimes/kotlin-1.9/src/main/kotlin/io/openruntimes/kotlin/Server.kt
tests/resources/functions/kotlin-1.6/Tests.kt
tests/resources/functions/kotlin-1.8/Tests.kt
tests/resources/functions/kotlin-1.9/Tests.kt

Feat: Binaries Kotlin

---

runtimes/go-1.22/src/go.mod
runtimes/java-11.0/src/main/java/io/openruntimes/java/RuntimeContext.java
runtimes/java-17.0/src/main/java/io/openruntimes/java/RuntimeContext.java
runtimes/java-18.0/src/main/java/io/openruntimes/java/RuntimeContext.java
runtimes/java-21.0/src/main/java/io/openruntimes/java/RuntimeContext.java
runtimes/java-8.0/src/main/java/io/openruntimes/java/RuntimeContext.java
runtimes/kotlin-1.6/src/main/kotlin/io/openruntimes/kotlin/RuntimeContext.kt
runtimes/kotlin-1.8/src/main/kotlin/io/openruntimes/kotlin/RuntimeContext.kt
runtimes/kotlin-1.9/src/main/kotlin/io/openruntimes/kotlin/RuntimeContext.kt
runtimes/python-3.10/src/function_types.py
runtimes/python-3.11/src/function_types.py
runtimes/python-3.12/src/function_types.py
runtimes/python-3.8/src/function_types.py
runtimes/python-3.9/src/function_types.py
runtimes/python-ml-3.11/src/function_types.py
runtimes/ruby-3.0/src/types.rb
runtimes/ruby-3.1/src/types.rb
runtimes/ruby-3.2/src/types.rb
runtimes/ruby-3.3/src/types.rb
tests/Base.php

Related PR: https://github.com/open-runtimes/types-for-go/pull/5

Fix: linebreaks in Go

---

base-after.dockerfile
ci/runtimes.toml
runtimes/bun/versions/latest/helpers/server.sh
runtimes/cpp/versions/latest/helpers/server.sh
runtimes/dart/versions/latest/helpers/server.sh
runtimes/deno/versions/latest/helpers/server.sh
runtimes/dotnet/versions/latest/helpers/server.sh
runtimes/go/versions/latest/helpers/server.sh
runtimes/java/versions/latest/helpers/server.sh
runtimes/kotlin/versions/latest/helpers/server.sh
runtimes/node/versions/latest/helpers/server.sh
runtimes/php/versions/latest/helpers/server.sh
runtimes/python/versions/latest/helpers/server.sh
runtimes/ruby/versions/latest/helpers/server.sh
runtimes/swift/versions/latest/helpers/server.sh

Helper bash script to start server script inside runtime.

Feat: Start helper

---

.github/workflows/test.yaml
ci/index.ts
runtimes/bun/versions/latest/src/server.ts
runtimes/dart/versions/latest/src/server.dart
runtimes/dotnet/versions/6.0/src/Program.cs
runtimes/dotnet/versions/7.0/Program.cs
runtimes/dotnet/versions/8.0/Program.cs
runtimes/go/versions/latest/src/main.go
runtimes/node/versions/latest/src/server.js
runtimes/php/versions/latest/src/server.php
runtimes/python/versions/latest/src/server.py
runtimes/ruby/versions/latest/src/server.rb
tests/Base.php
tests/resources/functions/node/latest/tests.js
tests/resources/functions/ruby/3.0/awaited_sleep.rb
tests/resources/functions/ruby/latest/awaited_sleep.rb
tests/resources/functions/ruby/latest/tests.rb

Ensure all those tests exist in Open Runtimes:
18MB request body works fine (including content correctness using md5)
22MB request body results in failure
Also improved file change detection during CI/CD, to re-run all tests of a global file changed.

Quality: Payload size tests (req&res)

---

runtimes/python/versions/latest/helpers/server.sh
runtimes/python/versions/latest/requirements.txt
runtimes/python/versions/latest/src/server.py

- Use gunicorn with proper thread setting per-code
- Remove unnessessary async

Feat: Improve python performance

---

runtimes/python/versions/latest/helpers/server.sh

Faster starts on python runtime.
See https://docs.gunicorn.org/en/stable/settings.html#preload-app

feat: preload gunicorn

---

base-before.dockerfile
tests/Base.php

Used for streaming logs with colors and timings

Feat: Add script CLI

---

ci/runtimes.toml
runtimes/ssr/ssr.dockerfile
runtimes/ssr/versions/latest/helpers/analog/server.sh
runtimes/ssr/versions/latest/helpers/angular/server.sh
runtimes/ssr/versions/latest/helpers/astro/server.sh
runtimes/ssr/versions/latest/helpers/next-js/server.sh
runtimes/ssr/versions/latest/helpers/nuxt/server.sh
runtimes/ssr/versions/latest/helpers/remix/server.sh
runtimes/ssr/versions/latest/helpers/sveltekit/server.sh
runtimes/ssr/versions/latest/package-lock.json
runtimes/ssr/versions/latest/package.json
runtimes/ssr/versions/latest/src/logger.js
runtimes/ssr/versions/latest/src/server-next-js.js
runtimes/ssr/versions/latest/src/server-remix.js
runtimes/ssr/versions/latest/src/server.js
tests/resources/functions/next-js/src/app/exception/page.js
tests/resources/functions/next-js/src/app/logs/page.js
tests/resources/functions/remix/app/routes/exception.tsx
tests/resources/functions/remix/app/routes/logs.tsx

Log tests in Remix and Next.js were failing, they weren't implemented properly.
To fix we need to switch to custom HTTP server that uses SSR handler.
This PR does exactly that, resolving all tests to become green.

Fix: React logs

---

ci/index.ts
ci/runtimes.toml
formatter.sh
runtimes/ssr/ssr.dockerfile
runtimes/ssr/versions/latest/helpers/astro/server.sh
runtimes/ssr/versions/latest/helpers/next-js/bundle.sh
runtimes/ssr/versions/latest/helpers/nuxt/server.sh
runtimes/ssr/versions/latest/helpers/remix/bundle.sh
runtimes/ssr/versions/latest/helpers/sveltekit/server.sh
runtimes/ssr/versions/latest/src/server-astro.js
runtimes/ssr/versions/latest/src/server-next-js.js
runtimes/ssr/versions/latest/src/server-nuxt.js
runtimes/ssr/versions/latest/src/server-remix.js
runtimes/ssr/versions/latest/src/server-sveltekit.js
tests/resources/functions/astro/astro.config.mjs
tests/resources/functions/astro/src/env.d.ts
tests/resources/functions/sveltekit/package.json
tests/resources/functions/sveltekit/svelte.config.js

Where possible, I applied adapter approach.
This makes cold-start faster, because we don't need proxy. It also gives more control over SSR server, which will be helpful in near future for solving concurrent logs

Feat: Adapter-approach in frameworks

---

runtimes/ssr/versions/latest/helpers/analog/env.sh
runtimes/ssr/versions/latest/helpers/analog/server.sh
runtimes/ssr/versions/latest/src/server-analog.js
tests/resources/functions/analog/vite.config.ts.timestamp-1735123273845-267a428075366.mjs

Uses handler approach to avoid the need to use proxy with Analog SSR framework.
Makes it faster, and easier to add custom logic (like logging concurrency in near future)

Feat: Analog SSR  handler

---

ci/runtimes.toml
runtimes/ssr/versions/latest/helpers/angular/server.sh
runtimes/ssr/versions/latest/src/server-angular.js

Angular was last remaining that used proxy. Now all frameworks use handler approach, giving us great possibilities with login reliability and speed.

Feat: Angular handler approach

---

.github/workflows/publish.yaml

Release V4.1 for SSR/frameworks development without affecting current production

Chore: v4 RC release preps

---

.github/workflows/publish.yaml
ci_release.sh

Release script in `feat-ssr` didnt pass properly after recent changes. This PR addresses all issues and makes release work well

Fix: release scripts

---

runtimes/ssr/versions/latest/helpers/analog/server.sh
runtimes/ssr/versions/latest/helpers/angular/server.sh
runtimes/ssr/versions/latest/helpers/astro/env.sh
runtimes/ssr/versions/latest/helpers/astro/server.sh
runtimes/ssr/versions/latest/helpers/next-js/server.sh
runtimes/ssr/versions/latest/helpers/nuxt/server.sh
runtimes/ssr/versions/latest/helpers/remix/server.sh
runtimes/ssr/versions/latest/helpers/sveltekit/server.sh
tests/resources/functions/astro/astro.config.mjs

Contonues on previous PR, ensuring Astro works with standole mode in code, and env vars are enforced during start of the runtime

Fix: Restarts crashing

---

ci_tests.sh
runtimes/ssr/versions/latest/package-lock.json
runtimes/ssr/versions/latest/package.json
runtimes/ssr/versions/latest/src/helpers.js
runtimes/ssr/versions/latest/src/logger.js
tests/Base.php
tests/Client.php
tests/SSR.php
tests/SSR/Analog.php
tests/SSR/Angular.php
tests/Serverless.php
tests/resources/functions/analog/src/app/app.config.ts
tests/resources/functions/analog/src/app/pages/concurrency.page.ts
tests/resources/functions/analog/src/app/pages/concurrency.server.ts
tests/resources/functions/astro/src/pages/concurrency.astro
tests/resources/functions/next-js/src/app/concurrency/page.js
tests/resources/functions/nuxt/pages/concurrency.vue
tests/resources/functions/remix/app/routes/concurrency.tsx
tests/resources/functions/sveltekit/src/routes/concurrency/+page.server.js
tests/resources/functions/sveltekit/src/routes/concurrency/+page.svelte

Uses a library that adds context to coroutines to correctly track log IDs for each request.

Feat: Concurrent SSR Logging

---

ci_tests.sh
runtimes/static/static.dockerfile
runtimes/static/versions/latest/404.html
runtimes/static/versions/latest/helpers/server.sh
tests/Base.php
tests/XStatic.php
tests/resources/functions/static/latest/resources/404.html

Configurable SPA behaviour - with or without fallback file.
Default fallback file overridable with `/mnt/resources/404.html`

Feat: SPA cofiguration
