- .travis.yml
The official deno image does not support the arm architecture at the moment. Hence removing those from the target.
> feat: remove dart unsupported architectures

- runtimes/dart-2.12/Dockerfile
- runtimes/dart-2.13/Dockerfile
- runtimes/dart-2.14/Dockerfile
- runtimes/dart-2.15/Dockerfile
Dart runtimes use a different `entrypoint` compared to the other runtimes. 
This PR fixes it
> fix: make entrypoints consistent

- runtimes/php-8.0/server.php
- runtimes/php-8.1/server.php
Problematic code:
```
<?
function myFunc() {
return "myFunc";
}
return function($req, $res) {
$res->json([ 'n' => \mt_rand() / \mt_getrandmax() ]);
};
```
Failed due to:
```
Fatal error: Cannot redeclare myFunc() (previously declared in /usr/code-start/index.php:4) in /usr/code-start/index.php on line 3
```
This PR makes sure we only import the code once, and share it between executions. Code above now works.
> Fix: Implemented one-time include

- runtimes/node-14.5/README.md
- runtimes/node-14.5/server.js
- runtimes/node-15.5/README.md
- runtimes/node-15.5/server.js
- runtimes/node-16.0/README.md
- runtimes/node-16.0/server.js
- runtimes/node-17.0/README.md
- runtimes/node-17.0/server.js
Improved docs of Node runtimes, to mention reserved keyword `code`. People should avoid using this, as this is not consistent behaviour in all runtimes.
> Docs: Node reserved key

- runtimes/node-14.5/server.js
- runtimes/node-15.5/server.js
- runtimes/node-16.0/server.js
- runtimes/node-17.0/server.js
Issue: https://github.com/open-runtimes/open-runtimes/issues/63
If you have `index.ts`:
It will build to `index.js`:
OPR for Node now supports this, and executes properly:
> Feat: ES module support (Node)

- runtimes/java-11.0/build.gradle
- runtimes/java-17.0/build.gradle
- runtimes/java-18.0/build.gradle
The `sourceCompatibility` for our Java 11, 17 and 18 runtimes were stuck at Java 8 which prevented us from using new Java features like the `var` declarations. 
This PR upgrades the `sourceCompatibility` flag to Java 11 to ensure better support for new features.
<details> 
<summary>Detailed Logs</summary>
```bash
Docker Error: /usr/local/src/src/main/java/io/openruntimes/java/Wrapper.java:25: warning: as of release , 'var' is a restricted type name and cannot be used for type declarations or as the element type of an array
var client = new Client();
^
/usr/local/src/src/main/java/io/openruntimes/java/Wrapper.java:28: warning: as of release , 'var' is a restricted type name and cannot be used for type declarations or as the element type of an array
var account = new Account(client);
^ …
```
> feat: increase source compatibility for newer Java versions

- runtimes/dart-2.15/example/lib/main.dart
- runtimes/dart-2.16/example/lib/main.dart
- runtimes/dart-2.17/example/lib/main.dart
- tests/dart-2.15/lib/tests.dart
- tests/dart-2.16/lib/tests.dart
- tests/dart-2.17/lib/tests.dart
Because `status` is optional, the correct syntax for how to pass the status is like this:
```dart
res.json({"attr": "value"}, status: 200);
```
This change updates the comment to help make that clear, especially since there is no type on the res parameter.
None
* 
Yes
> Fix helper comment of dart res.send() and res.json()

- docs/add-runtime.md
There's a typo in the add-runtime.md file according to this [test case](https://github.com/open-runtimes/open-runtimes/blob/main/tests/Base.php#L108)
> Fix add-runtime.md

- runtimes/java-11.0/src/main/java/io/openruntimes/java/Server.java
- runtimes/java-17.0/src/main/java/io/openruntimes/java/Server.java
- runtimes/java-18.0/src/main/java/io/openruntimes/java/Server.java
- runtimes/java-8.0/src/main/java/io/openruntimes/java/Server.java
This PR adds small changes to the java runtimes to handle status codes differently:
- ~~Unauthorized requests result in a 401 code (instead of 500 prior)~~
- Setting the statuscode in RuntimeResponse now correctly sets the code on the http response
Related: #108
> Fix Java statuscode usage

- runtimes/swift-5.5/dependencies.swift
When merging dependencies, we're adding an extra comma between dependencies which leads to a syntax error.
Fixes: https://github.com/appwrite/appwrite/issues/5863
> Fix swift build for multiple dependencies

- .travis.yml
Bun base image supports those archs:
> https://hub.docker.com/r/oven/bun/tags
So I ensure we have same supported in Appwrite. It's also standard for us to support these 2 archs, as seen in in other rutimes.
> Feat: Bun ARM support

- runtimes/python-3.10/requirements.txt
- runtimes/python-3.11/requirements.txt
- runtimes/python-3.8/requirements.txt
- runtimes/python-3.9/requirements.txt
Flask seems to fail to run:
```
Traceback (most recent call last):
File "/usr/local/server/src/server.py", line 1, in <module>
from flask import Flask, request, Response as FlaskResponse
File "/usr/local/server/src/function/runtime-env/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
from .app import Flask as Flask
File "/usr/local/server/src/function/runtime-env/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
from . import cli
File "/usr/local/server/src/function/runtime-env/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
from .helpers import get_debug_flag
File "/usr/local/server/src/function/runtime-env/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
from werkzeug.urls import url_quote
ImportError: cannot import …
```
> Fix: Python Flask issues

- runtimes/go-1.22/Dockerfile
Fixes:
Failed to execute command: {"ID":"1affbbe77311fc34b48396a63fc565e8e7c1cb2ab5608a218eff8aa0225e609f","Running":false,"ExitCode":126,"ProcessConfig":{"tty":false,"entrypoint":"sh","arguments":["-c","touch /var/tmp/logs.txt && (tar -zxf /tmp/code.tar.gz -C /mnt/code && helpers/build.sh "") >> /var/tmp/logs.txt 2>&1 && cat /var/tmp/logs.txt"],"privileged":false},"OpenStdin":false,"OpenStderr":true,"OpenStdout":true,"CanRemove":false,"ContainerID":"3feb5ea15d58dc5e8a7352dd65c94d79ff98b5badd2f21bde23daa3608da88dd","DetachKeys":"","Pid":874797}
Exit Code: 126sh: helpers/build.sh: Permission denied
> Fix: go permissions

- runtimes/go-1.22/README.md
- runtimes/go-1.22/example/go.mod
- runtimes/go-1.22/src/go.mod
- tests/resources/functions/go-1.22/go.mod
- tests/resources/functions/go-1.22/tests.go
Upgrade types lib, and ensure error class now prints well. Before it just printed `{}`
> Chores: Improve Go tests for native Errors

- runtimes/go/README.md
- runtimes/go/versions/latest/src/go.mod
- runtimes/go/versions/latest/src/go.sum
- runtimes/go/versions/latest/src/main.go
- tests/resources/functions/go/latest/go.mod
- tests/resources/functions/go/latest/go.sum
- tests/resources/functions/go/latest/tests.go
Makes import of types without alias - more common approach across Go community
> Feat: Upgrade namespacing

- runtimes/php/versions/latest/src/types.php
- tests/resources/functions/bun/latest/tests.ts
- tests/resources/functions/cpp/latest/tests.cc
- tests/resources/functions/dart/latest/lib/tests.dart
- tests/resources/functions/deno/latest/tests.ts
- tests/resources/functions/dotnet/6.0/Tests.cs
- tests/resources/functions/dotnet/7.0/Tests.cs
- tests/resources/functions/dotnet/8.0/Tests.cs
- tests/resources/functions/go/latest/tests.go
- tests/resources/functions/java/11.0/Tests.java
- tests/resources/functions/java/8.0/Tests.java
- tests/resources/functions/java/latest/Tests.java
- tests/resources/functions/kotlin/latest/Tests.kt
- tests/resources/functions/node/latest/tests.js
- tests/resources/functions/node/latest/tests.mjs
- tests/resources/functions/php/latest/tests.php
- tests/resources/functions/python/latest/tests.py
- tests/resources/functions/python/ml-3.11/tests.py
- tests/resources/functions/ruby/latest/tests.rb
- tests/resources/functions/swift/latest/Sources/Tests.swift
In PHP bodyText was not working at all. Test was not checking it.
Tests were missing in many other runtimes too.
Also fixed deprecated uses of `send` instead of `text` in tests. Send still tested, but only in deprecated tests
> Fix: context.req.bodyText

- runtimes/deno/versions/1.40/Dockerfile
- runtimes/go/versions/1.23/Dockerfile
- runtimes/node/versions/14.5/Dockerfile
- runtimes/node/versions/19.0/Dockerfile
- runtimes/php/versions/8.0/Dockerfile
- runtimes/php/versions/8.1/Dockerfile
- runtimes/php/versions/8.2/Dockerfile
- runtimes/php/versions/8.3/Dockerfile
- runtimes/python/versions/3.10/Dockerfile
- runtimes/python/versions/3.11/Dockerfile
- runtimes/python/versions/3.12/Dockerfile
- runtimes/python/versions/3.8/Dockerfile
- runtimes/python/versions/3.9/Dockerfile
- runtimes/python/versions/ml-3.11/Dockerfile
- runtimes/ruby/versions/3.0/Dockerfile
- runtimes/ruby/versions/3.1/Dockerfile
- runtimes/ruby/versions/3.2/Dockerfile
- runtimes/ruby/versions/3.3/Dockerfile
- Deno used 1.41 instead of 1.40, fixed
- Lock Go, PHP, Python, Ruby, Node to specific patch versions
> Fix: Version consistency

- .github/workflows/publish.yaml
Add newly supported archs (1.35 doesnt support it).
This adds support for MacOS (Appwrite CLI)
Proof 1.35 doesn't have it:
Proof 1.40 has it:
I also checked each 3 versions
> Fix: Deno release cpu archs

- .github/workflows/publish.yaml
With the addition of gunicorn and aiohttp, we are no longer able to install them on arm/v6 and arm/v6 platforms since gcc is not readily available and needs to be compiled from source for those platforms.
> chore: update python deployment target architectures

- runtimes/python/versions/latest/helpers/server.sh
While investigating https://github.com/appwrite/appwrite/issues/8907, we noticed logs like:
```
Preparing for start ...
Starting ...
HTTP server successfully started!
[2024-11-05 09:25:59 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:17)
[2024-11-05 09:26:00 +0000] [16] [ERROR] Worker (pid:17) was sent SIGKILL! Perhaps out of memory?
```
So, the worker probably timed out since the default [timeout](https://docs.gunicorn.org/en/stable/settings.html#timeout) is 30 seconds and then there was no reply sent back to Appwrite.
This PR changes the timeout in gunicorn to prevent the workers from being killed and Appwrite will handle the timeout.
> chore: disable gunicorn timeout

- runtimes/bun/versions/latest/src/server.ts
- runtimes/node/versions/latest/src/server.js
Sets idleTimeout setting in Bun: https://bun.sh/docs/api/http#idletimeout
This may be causing worker threads to exit, and throw curl error 52 on the client.
Related:
* https://github.com/appwrite/appwrite/issues/8907
> fix: 52 timeouts

- ci_release.sh
Release is broken: https://github.com/open-runtimes/open-runtimes/actions/runs/12014222549
I took code from test logic: https://github.com/open-runtimes/open-runtimes/blob/3dafc49e9863a4b09c2cc2bd27f44b7389036fae/ci_tests.sh#L4-L6
> Fix: cicd task for release

- ci_tests.sh
- runtimes/java/java.dockerfile
- runtimes/swift/swift.dockerfile
- runtimes/swift/versions/5.10/Dockerfile
- runtimes/swift/versions/5.5/Dockerfile
- runtimes/swift/versions/5.8/Dockerfile
- runtimes/swift/versions/5.9/Dockerfile
Add test to ensure `unzip` and `tar` are available in All runtimes
Swift changes are due to:
(swift 5.5 got different because that version didn't exist when swift 5.5 was released)
> Feat: Compression algos support

- runtimes/ssr/versions/latest/helpers/analog/server.sh
- runtimes/ssr/versions/latest/helpers/angular/server.sh
- runtimes/ssr/versions/latest/helpers/astro/server.sh
- runtimes/ssr/versions/latest/helpers/next-js/server.sh
- runtimes/ssr/versions/latest/helpers/nuxt/server.sh
- runtimes/ssr/versions/latest/helpers/remix/server.sh
- runtimes/ssr/versions/latest/helpers/sveltekit/server.sh
`mv` command doesnt work well when restarting after crash. Using `cp` instead solves this problem.
> Fix: SSR runtime restarts
